project:
  type: website

website:
  title: "Ahsan's Blog"
  navbar:
    title: false
    pinned: true
    right:
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/ahsanmah

format:
  html:
    theme: journal 
      # dark: darkly
    css: styles.css



