project:
  type: website

website:
  title: "Ahsan's Blog"
  open-graph: true
  navbar:
    title: false
    pinned: true
    right:
      - index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/ahsanmah
  google-analytics:
    tracking-id: "G-LMZYEG4JP1"
    anonymize-ip: true
    storage: none

format:
  html:
    theme:
      light: journal
      dark: darkly

